# The drillsbuddy-device application, frozen - the part shared by every
# DRILLSBUDDY image (ESP32-C6, ESP32-C3: ports/esp32/boards/
# manifest_drillsbuddy.py; Pico W: ports/rp2/boards/manifest_drillsbuddy.py),
# each of which first includes its port's/board's own manifest. The sibling
# checkout is expected at ../drillsbuddy-device relative to this MicroPython
# tree, or set DRILLSBUDDY_DEVICE_DIR.
import os

# manifestfile.py runs an included manifest with its own directory as cwd
# (drillsbuddy/ in the MicroPython tree).
_mpy_dir = os.path.abspath(os.path.join(os.getcwd(), ".."))
_device = os.environ.get("DRILLSBUDDY_DEVICE_DIR") or os.path.normpath(
    os.path.join(_mpy_dir, "..", "drillsbuddy-device")
)
_src = os.path.join(_device, "src")
# main.py stays a file on flash (MicroPython only runs main.py from the
# filesystem); board_config.py is generated per device and flashed as a
# file; neither is frozen.
_skip = {"main.py", "board_config.py"}
_modules = sorted(
    f
    for f in os.listdir(_src)
    if f.endswith(".py") and f not in _skip and os.path.isfile(os.path.join(_src, f))
)
freeze(_src, _modules)
_imu = os.path.join(_device, "micropython-mpu9x50")
freeze(_imu, ["imu.py", "vector3d.py"])

# drillsbuddy_build: a generated module recording the hash of exactly the
# files frozen above (plus the device commit and build time), so the pod can
# tell scripts/flash.sh which src/ its image was built from - flash.sh then
# rebuilds/reflashes the image only when that differs from the checkout.
# Generated by the device repo's own scripts/src_hash.py (the single
# definition of that hash, shared with flash.sh) into its gitignored build/.
import subprocess
import sys

_build_module = os.path.join(_device, "build", "drillsbuddy_build.py")
subprocess.run(
    [
        sys.executable,
        os.path.join(_device, "scripts", "src_hash.py"),
        "--device-dir",
        _device,
        "--write-module",
        _build_module,
    ],
    check=True,
    stdout=subprocess.DEVNULL,
)
freeze(os.path.dirname(_build_module), ["drillsbuddy_build.py"])
